### PR TITLE
Fix mining of Stone Brick Furnace to give XM item instead of base item

### PR DESCRIPTION
**Pull request by mspielberg**
Consolidate on using the furnace-1 entity (XM assembling-machine supporting the "kiln" crafting category), and the base game's stone-furnace-item.
Removes the dummy furnace-1 item that was never intended to be accessible, but was yielded when mining a stone-furnace entity.

Fixes issue #17.

### CODE REVIEW

**Comment by mspielberg** [comment]
Before this change, crafting a Stone Brick Furnace gave a stone-furnace item in inventory, which resulted in a furnace-1 assembling machine entity on the ground when placed. Mining that furnace-1 entity gave a furnace-1 item in inventory. Placing that furnace-1 item would result in a vanilla stone-furnace furnace entity on the ground, which was useless since it had no crafting categories enabled. Mining the stone-furnace entity yielded a stone-furnace item in inventory, closing the loop.

It looks like the furnace-1 item was never supposed to be accessible in the first place, hence the "placeholder item" comment. Factorio complains if an entity has the "placeable-player" or similar flags on an entity, but there is no matching item to place it. The vanilla stone-furnace has this flag, but XM uses assembling machines entities, not furnace entities, for smelting. By removing the "placeable-*" flags from the stone-furnace entity, we can also remove the inventory item for it (furnace-1), and simplify this whole area.

The migration JSON file makes sure that any leftover "furnace-1" items and "stone-furnace" entities in the world are converted to the correct versions.

**Comment by jodokus31** [comment]
OK, i wonder, why should it be more complicated than changing the Blast furnace to an XM assembly type. And I think, its because of the player's default starting items. Maybe the players starting "stone-furnace" item could be removed. and instead have a furnace-1

**Comment by Gragorath** [comment]
Uh, this might be my bad. In the patch I posted on the forum, which ironchefpython commited verbatim to the git repository, I fixed a similar issue with the electric foundry forge. I "fixed" the stone furnace in the same pass (minable = "stone-furnace" -> "furnace-1") without much consideration, and here we are. Guess I was too focused on the foundry forge to verify that change.

**Comment by mspielberg** [comment]
One argument for keeping base item names is mod compatibility. If someone wants to use the My Custom Super Awesome Furnace mod with XM, which includes a recipe with stone-furnace as an ingredient, it's handy to have that item still be craftable. The opposite side of the argument is consistency of naming, since XM currently has stone-furnace, furnace-2, furnace-3, etc.

Adhering to consistency would require that we change to the furnace-1 item and make the base stone-furnace item inaccessible. Going for cross-mod compatibility would suggest moving back to the items steel-furnace, electric-furnace, and so on throughout the mod.

**Comment by Repofme1** [comment]
Hi there -

Sorry for not recognizing this until now, but I just realized what's going on, and now I understand the problem.  I'd like to go for the approach of re-using the base item for the XM entity, since that has been my style in most cases (items like iron-plate and explosives, technologies like advanced-material-processing and electronics).

Removing the placeable-* tags like @mspielberg said would be a more elegant solution, much better than the never-accessible placeholder item that I currently have.  I used that originally since I didn't know to remove the appropriate tags as a better way of dealing with the placement item requirement.

Sorry it took so long to get to this, it was just a matter of available time and focus.  Other changes have caused conflicts with this request by now, so I don't know if it would be better to fix the code in this PR, or for me to just re-build it as a commit from my end.  In either case, I'd like to apply this same fix with the tags and single item to the steel and electric furnaces as well as the stone one.  Other than that I don't really mind which source we make the changes from - a single commit from me might be more straightforward, but using the PR gives people the appropriate credit and helps me practice GitHub.

**Comment by mspielberg** [comment]
Superseded by mainline change.

**Pull request closed without merging**
